<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('Официальный сайт Павла Шумила'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    </head>
    <body>
      <div id="wrap">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://dragonbase.info">
                        <?= $this->translate('Сайт Павла Шумила') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= $this->translate('About') ?><b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('Об авторе') ?></a></li>
                                <li><a href="<?php echo $this->url('about/bibliography') ?>"><?php echo $this->translate('Библиография') ?></a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('books') ?>"><?php echo $this->translate('Книги') ?></a></li>
                        <li><a href="<?php echo $this->url('fairwind') ?>"><?php echo $this->translate('Попутный ветер') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
      </div>
      <footer id="footer">
        <div class="container">
            <div class="pull-right copyright">&copy; 1994-<?php echo date('Y') ?> Павел Робертович Шумилов</div>
            <div class="clearfix"></div>
            <div class="pull-left">
                <a class="small" href="https://github.com/Dragonbase/Dragonbase.github.io/issues/new">
                    Нашли ошибку на сайте?
                </a>
            </div>
            <div class="powered-by small">Powered by <a class="zf-green" href="http://framework.zend.com">Zend Framework 2<span class="icon-zf2"></span></a></div>
        </div>
      </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
